export const SET_TOKEN = 'SET_TOKEN';
export const SET_ISAUTH = 'SET_ISAUTH';
export const SET_LOGOUT = 'SET_LOGOUT';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_IS_ADMIN = 'SET_IS_ADMIN';
export const SET_UNREAD_BULLETIN = 'SET_UNREAD_BULLETIN';

export const SET_LOGIN = 'SET_LOGIN';
export const SET_TOKEN_LOGIN = 'SET_TOKEN_LOGIN';

export const SET_BEGIN_TIME = 'SET_BEGIN_TIME';
export const SET_END_TIME = 'SET_END_TIME';
export const SET_IS_REGISTER_OPEN = 'SET_IS_REGISTER_OPEN';

export const SET_OPEN_CHALLENGE = 'SET_OPEN_CHALLENGE';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_SOLVED_CHALLENGE = 'SET_SOLVED_CHALLENGE';
export const ADD_SOLVED_CHALLENGE = 'ADD_SOLVED_CHALLENGE';
export const ADD_CHALLENGE_DETAIL = 'ADD_CHALLENGE_DETAIL';
export const CLEAR_CHALLENGE = 'CLEAR_CHALLENGE';

export const SET_BULLETIN = 'SET_BULLETIN';

export const SET_CREATED_CONTAINER = 'SET_CREATED_CONTAINER';
export const ADD_CREATED_CONTAINER = 'ADD_CREATED_CONTAINER';
export const ADD_CONTAINER_INFO = 'ADD_CONTAINER_INFO';
export const DELETE_CONTAINER_INFO = 'DELETE_CONTAINER_INFO';
export const CLEAR_CONTAINER = 'CLEAR_CONTAINER';
